### ISSUE TITLE
Error when pynews is installed globally and then executed

### ISSUE THREAD

**Issue by mazulo** [mazulo/pynews_cli#9]
Traceback:

``` bash
# mazulo @ in ~ [22:07:34] 
$ pynews --help
Traceback (most recent call last):
  File "/usr/bin/pynews", line 11, in <module>
    load_entry_point('PyNews==0.2', 'console_scripts', 'pynews')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2608, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2268, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2274, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/pynews/pynews.py", line 6, in <module>
    import requests as req
  File "/usr/lib/python3.5/site-packages/requests/__init__.py", line 60, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name 'DependencyWarning'
```

**Comment by drgarcia1986** [comment]
take a look at https://github.com/nickoala/telepot/issues/80

**Comment by mazulo** [comment]
@drgarcia1986 Yeah, that was the solution! Thanks, dude 😎
